package gov.usgs.cida.gdp.wps.algorithm.heuristic;

import gov.usgs.cida.gdp.wps.algorithm.heuristic.exception.AlgorithmHeuristicException;

/**
 * This interface provides a means to encapsulate multiple algorithm heuristics
 * into a single container for processing.  It is meant to be extremely basic
 * in order to allow as much freedom as necessary in the implementing classes.
 * @author prusso
 *
 */
public interface AlgorithmHeuristic {
    /**
     * This method processes the internal logic of a Heuristic and returns
     * whether the necessary algorithm requirements or restrictions have been
     * met.
     * @return whether the heuristic was validated or not
     * @throws AlgorithmHeuristicException 
     */
    public boolean validated() throws AlgorithmHeuristicException;
    
    /**
     * This method returns the error generated by the heuristic if validation
     * was not successful.  If the heuristic had not been processed or it is
     * valid, it returns an empty string.
     * @return error causing invalidation or empty string
     */
    public String getError();
}
